#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import webbrowser
import ipynb_open


def main(path):
    url = ipynb_open.resolve_url(path)
    webbrowser.open(url)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("ipynb_path")
    args = parser.parse_args()
    main(args.ipynb_path)
